# SPDX-FileCopyrightText: 2021 Tobias Fella <fella@posteo.de>
# SPDX-License-Identifier: BSD-2-Clause

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kirigami': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kconfig': '@latest'
    'libraries/kirigami-addons': '@latest'
    'frameworks/qqc2-desktop-style': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/baloo': '@latest'
    'frameworks/kfilemetadata': '@latest'
    'frameworks/kdbusaddons': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
