# SPDX-FileCopyrightText: 2021 Tobias Fella <fella@posteo.de>
# SPDX-License-Identifier: BSD-2-Clause

Dependencies:
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kfilemetadata': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kquickcharts': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
   'require':
    'frameworks/baloo': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
